#!C:\Users\elvis_d\DATA_ANALYTICS\GITHUB\AZUBI AFRICA TMP ASSESSMENT\AZUBI-AFRICA---TALENT-MOBILITY-PROGRAM-ASSESSMENT\env_tmp\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
